(function (namespace) {
    const byId = id => document.getElementById(id);
    const client = () => namespace.supabase && namespace.supabase.client;
    const setMessage = (text, error = false) => { const node = byId("authMessage"); node.textContent = text; node.classList.toggle("auth-error", error); };
    const errorMessage = error => { const text = String(error && error.message || "").toLowerCase(); if (text.includes("invalid login")) return "Correo o contraseña incorrectos."; if (text.includes("already")) return "Ya existe una cuenta con este correo."; if (text.includes("password")) return "La contraseña debe tener al menos 6 caracteres."; return "No se pudo conectar. Intenta nuevamente."; };
    function pending(form, value) { const button = form.querySelector('button[type="submit"]'); button.disabled = value; button.dataset.text ||= button.textContent; button.textContent = value ? "Procesando…" : button.dataset.text; }
    function updateUi(user) { const label = byId("authUserLabel"), open = byId("btnAbrirAuth"), account = byId("btnAbrirCuenta"), logout = byId("btnCerrarSesion"); if (user) { label.textContent = `Hola, ${(user.user_metadata && user.user_metadata.full_name) || user.email}`; label.hidden = false; open.hidden = true; account.hidden = false; logout.hidden = false; } else { label.hidden = true; open.hidden = false; account.hidden = true; logout.hidden = true; } if (namespace.account) namespace.account.handleAuthState(user); }
    function show(mode) { const login = byId("loginForm"), register = byId("registerForm"); login.hidden = mode !== "login"; register.hidden = mode !== "register"; byId("authModalTitle").textContent = mode === "login" ? "Ingresar" : "Crear cuenta"; setMessage(""); (mode === "login" ? byId("loginEmail") : byId("registerName")).focus(); }
    function close() { const modal = byId("authModal"); modal.hidden = true; modal.setAttribute("aria-hidden", "true"); }
    function open(mode = "login") { const modal = byId("authModal"); modal.hidden = false; modal.setAttribute("aria-hidden", "false"); show(mode); }
    async function signUp(form) { const fullName = form.fullName.value.trim(), email = form.email.value.trim(), phone = form.phone.value.trim(), password = form.password.value; if (!client()) return setMessage("El acceso no está disponible en este momento.", true); if (!fullName || !email || !phone || !password) return setMessage("Completa todos los campos requeridos.", true); if (!form.email.checkValidity()) return setMessage("Ingresa un correo electrónico válido.", true); if (password.length < 6) return setMessage("La contraseña debe tener al menos 6 caracteres.", true); if (password !== form.passwordConfirm.value) return setMessage("Las contraseñas no coinciden.", true); pending(form, true); const { data, error } = await client().auth.signUp({ email, password, options: { data: { full_name: fullName, phone } } }); pending(form, false); if (error) return setMessage(errorMessage(error), true); form.reset(); setMessage(data.session ? "Cuenta creada e iniciada correctamente." : "Cuenta creada. Revisa tu correo para confirmar tu cuenta."); }
    async function signIn(form) { const email = form.email.value.trim(), password = form.password.value; if (!client()) return setMessage("El acceso no está disponible en este momento.", true); if (!email || !password) return setMessage("Completa correo y contraseña.", true); if (!form.email.checkValidity()) return setMessage("Ingresa un correo electrónico válido.", true); pending(form, true); const { error } = await client().auth.signInWithPassword({ email, password }); pending(form, false); if (error) return setMessage(errorMessage(error), true); close(); }
    async function signOut() { if (client()) await client().auth.signOut(); }
    async function init() { if (!client()) return; const { data } = await client().auth.getSession(); updateUi(data.session && data.session.user); client().auth.onAuthStateChange((_event, session) => updateUi(session && session.user)); }
    function bind() { byId("btnAbrirAuth").addEventListener("click", () => open()); byId("btnCerrarAuth").addEventListener("click", close); byId("btnCerrarSesion").addEventListener("click", signOut); byId("mostrarRegistro").addEventListener("click", () => show("register")); byId("mostrarLogin").addEventListener("click", () => show("login")); byId("loginForm").addEventListener("submit", event => { event.preventDefault(); signIn(event.currentTarget); }); byId("registerForm").addEventListener("submit", event => { event.preventDefault(); signUp(event.currentTarget); }); byId("authModal").addEventListener("click", event => { if (event.target === event.currentTarget) close(); }); document.addEventListener("keydown", event => { if (event.key === "Escape" && !byId("authModal").hidden) close(); }); }
    namespace.auth = { init, signUp, signIn, signOut, getSession: () => client() && client().auth.getSession(), getUser: () => client() && client().auth.getUser(), isAuthenticated: async () => client() ? Boolean((await client().auth.getSession()).data.session) : false };
    document.addEventListener("DOMContentLoaded", () => { bind(); init(); });
}(window.GoTienda = window.GoTienda || {}));
